### ISSUE TITLE
Delete Transaction

### ISSUE THREAD

**Issue by willatkova** [willatkova/makerpos-usergroup#10]
On the till, I would like a “delete transaction” button that deletes the entire transaction.  We often have customers who decide to keep shopping after we’ve started scanning and bugger off leaving a queue of waiting customers behind them.

**Comment by willatkova** [comment]
Once there are items in the basket, a "Clear Sale" action will show. 



![Image](https://github.com/willatkova/kovapos-usergroup/assets/54409295/6ad24976-5462-4d79-8e14-8c43f7b11676)

**Comment by willatkova** [comment]
It will prompt the user



![Image](https://github.com/willatkova/kovapos-usergroup/assets/54409295/dda3755a-17ea-4361-9ab2-c5ee5f903648)

**Comment by willatkova** [comment]
Is user agrees, it will clear the basket and alert the user



![Image](https://github.com/willatkova/kovapos-usergroup/assets/54409295/bf8ac56d-5128-473b-9158-1fe6e69ed762)

**Comment by Debs123V** [comment]
Fantastic.  What is the Park Sale function?

**Comment by Debs123V** [comment]
I see the % discount button there too.  This will pertain to a single item and not an entire transaction.  Just putting that out there so we're on the same page.

**Comment by willatkova** [comment]
> Fantastic. What is the Park Sale function?

Might not apply to your situation but if you don't want to complete a sale, you can "park" it and then bring it back later

**Comment by willatkova** [comment]
> I see the % discount button there too. This will pertain to a single item and not an entire transaction. Just putting that out there so we're on the same page.

Yup

**Comment by willatkova** [comment]
Sorted
