### ISSUE TITLE
Label Print Requests not updating accurately after printing

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#17]
![Screenshot 2024-10-09 123013](https://github.com/user-attachments/assets/2991f1e8-5d82-4844-a566-2209a65fc8a6)
Grace Glass labels were printed in full yesterday.  Still showing as Requested, and printed column is showing many unprinted.  All were definitely printed.

**Comment by willatkova** [comment]
Made a small change, looks like you can just send the label once, and add how many copies, instead of sending it each time. 
Have released it in 1.13.16, please test and let me know. If it doesn't work, we need to revert back to the old code, otherwise it will only print one label per product.

**Comment by willatkova** [comment]
@Debs123V confirmed it is working
