### ISSUE TITLE
New Maker Products List

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#18]
![image](https://github.com/user-attachments/assets/a06af841-6d02-4db4-8b12-e687722f0edd)

Under New Maker Products, there are items on the list for CROW and Aroma Soothz that were updated a while ago (not new products).  The pricing was changed on the Market side, as per a request by the Makers prior to them having access.  

The prices showing up on this list are the old prices, which will probably be what the Makers have on their side.  These items need to be updated on the Maker side as per the current Market price.

**Comment by willatkova** [comment]
Please test this in 1.13.15

**Comment by Debs123V** [comment]
![image](https://github.com/user-attachments/assets/bfcc536f-6653-44b5-9823-490b3d73ebfa)

Not sure how to test this, but the items are still showing up under New Products, with the incorrect (old) price attached.

**Comment by willatkova** [comment]
Sorted this out, please check if it is clear now
