### ISSUE TITLE
New Maker Products List - Ignore Column

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#19]
![image](https://github.com/user-attachments/assets/8b44fb66-1a13-48d7-928d-d95dc99030d6)

When Makers add products by accident, I need to ignore them on my side.  These also need to be deleted on their side.

In this example, Fran Ridl created a product without a price, Mooshimoo forgot to add their prefix (for their own use) and so created another product (57MG Cat keeps you) which is live, Lens & Hues created two 54 Long earred bunny items at the same price.

It's one thing to ignore them on my side, but I don't want them trying to use these products on their side.

Perhaps the Maker needs a notification of what the Market has or hasn't done, so communication works both ways?

**Comment by willatkova** [comment]
Have started working on this, the new and updated lists both have ignore columns now. 
Need to just finish the back end part. 
This will add the products in a table on our side. 

When a Maker edits the product again, it will be removed from the ignore table, so you can see it again. 
Not sure how else to handle this, open to suggestions.

**Comment by willatkova** [comment]
Finished, please test in build 1.14.2

**Comment by Debs123V** [comment]
Ignored the CROW items but they keep popping back

**Comment by willatkova** [comment]
Fixing the New broke the Update. Both now working in 1.14.4
