### ISSUE TITLE
Changed Maker Products

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#20]
![image](https://github.com/user-attachments/assets/4317b21b-acdc-403d-a166-0df632284226)
 
These two Everything Laser items keep showing up on this list.  I select them, update them, they disappear.  Next day they're back!

**Comment by willatkova** [comment]
Have changed it to first force you to update from the server:

![Screenshot 2024-10-09 at 13 15 12](https://github.com/user-attachments/assets/670e8d2e-e483-4156-9be3-2a5c61ccd480)

Please test in build 1.13.14

**Comment by Debs123V** [comment]
Working.
