### ISSUE TITLE
Changed Maker Products - changed by Market

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#21]
![image](https://github.com/user-attachments/assets/1527d261-ddd6-43b7-ab11-98c616f33918)

The rest of the items from Nourish down have been changed by me on the Market side.  The prices shown here are the old prices that will reflect on the Maker side.  

The Maker side needs to be updated to the price currently on the Market side (not the price on this list).

Again, these changes were made by me on behalf of the Maker before they were on the system.  And before I understood that the 2 systems worked independently of each other.

**Comment by willatkova** [comment]
Changed these items

![Screenshot 2024-10-09 at 13 29 49](https://github.com/user-attachments/assets/c6aa4ffe-dbfb-4621-a543-6c1ec24df18a)

**Comment by Debs123V** [comment]
![image](https://github.com/user-attachments/assets/2a67ad48-d01c-41de-9f84-ebcf7d610229)

This one is still hanging on.  Price should be R120 I think.

**Comment by willatkova** [comment]
> ![image](https://private-user-images.githubusercontent.com/162784292/375423912-2a67ad48-d01c-41de-9f84-ebcf7d610229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjY2MzUsIm5iZiI6MTcyODYyNjMzNSwicGF0aCI6Ii8xNjI3ODQyOTIvMzc1NDIzOTEyLTJhNjdhZDQ4LWQwMWMtNDFkZS05Zjg0LWViY2Y3ZDYxMDIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwNTU4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGViNzA5MDRhYWFjNmUzMDRlYzQzMjEzY2I0NmRmZmZjZDE5YTA3ZDQwZjRhMGFkZTI5NTZjYmNmZDZlY2JhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.w1vj9D96cBbBUXpb5WGfWmn6L_imehT9PCbYQPvrUHU)
> 
> This one is still hanging on. Price should be R120 I think.

Sorted

**Comment by willatkova** [comment]
Deleted these products on both sides

![WhatsApp Image 2024-10-10 at 16 32 27](https://github.com/user-attachments/assets/38986675-ea42-4606-bc46-6912df119917)

**Comment by Debs123V** [comment]
Perfect.  Shall we close this one?
