### ISSUE TITLE
Market / Reports / Petty Cash

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#22]
Please can we have a petty cash report or add the petty cash transactions to the daily cash up report.

I need to see who I've paid cash, when and why.

**Comment by willatkova** [comment]
Added Petty Cash Report in build 1.14.0

![Screenshot 2024-10-14 at 13 54 25](https://github.com/user-attachments/assets/84502463-04dd-4cd6-a7d0-fbe963f54b04)

![Screenshot 2024-10-14 at 13 54 34](https://github.com/user-attachments/assets/02690cc6-887e-47d9-84cb-cfec98f9b9d7)

**Comment by Debs123V** [comment]
Works like a dream!!
