### ISSUE TITLE
Market / Reports / Supplier Sales

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#23]
Please can we add a search bar in the supplier drop down.
Please can we change the summary on the bottom of the supplier report to per product (qty) and not per date (transactions).

**Comment by willatkova** [comment]
Report now grouped by Product

![Screenshot 2024-10-14 at 13 05 57](https://github.com/user-attachments/assets/1a082d66-f3dc-4c82-8a02-0bddffc46d72)

**Comment by willatkova** [comment]
Maker Select Modal now has filter

![Screenshot 2024-10-14 at 13 04 08](https://github.com/user-attachments/assets/ff5e2f84-189f-4da4-aced-d9a0810cf9ed)

**Comment by Debs123V** [comment]
Fantastic!
