### ISSUE TITLE
Watercrest Cashup 9 Oct

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#24]
All card transactions match the sales for the day.  The first sale was R76.  We are R76 over on cash up.  Please check if there is a bug here.

Cash up on 10 Oct - The R76 transaction seems to have come back.  We are R258 under, but there was a transaction for R182 that was declined on the card machine and the cashier missed it and let it go.

**Comment by willatkova** [comment]
The R76 was cashed up in the next day's cashup. Have we deleted the app at Watercrest, rather let them use the browser.

![Screenshot 2024-10-13 at 07 14 41](https://github.com/user-attachments/assets/50aee1be-d65f-408c-82eb-a3866d7de816)

**Comment by Debs123V** [comment]
Currently using the browser at Watercrest.  Will monitor the cashups.
