### ISSUE TITLE
Grace Glass Products

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#25]
I don't know wtf she did when creating her products but it's a mess.

![image](https://github.com/user-attachments/assets/527ed9eb-311b-491a-a893-b82d1c7c4a18)
 These are the items we printed.  I see the SKU is all Grace Glass....these people cannot be trusted with the SKU.  We literally have to take that away and autogenerate.  Full stop.

**Comment by willatkova** [comment]
Have fixed her skus in products and labels.
Will change lock the skus down more in tomorrow's build

**Comment by willatkova** [comment]
Have changed this in build 1.14.3:

SKU is auto-generated and cannot be edited:

![Screenshot 2024-10-14 at 18 23 37](https://github.com/user-attachments/assets/2daec773-7d88-4d3f-b4ba-6999a5ed7555)

Can now also delete product:

![Screenshot 2024-10-14 at 18 23 48](https://github.com/user-attachments/assets/56ac7210-609f-435c-a972-74224ad00b34)

**Comment by Debs123V** [comment]
How will deleting a product affect the transaction history?
