### ISSUE TITLE
Importing New Maker Products

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#27]
Bulk importing of new maker products is struggling.  Once I select a list of items and click Import X Products, there is no reaction.  If I wait, sometimes it imports, sometimes it doesn't.  If I click import again, no reaction.  Move off that screen and come back - and half of the items have imported.

I will leave G&T Creationz on there for you to check.  This happened with her list.  I selected all her new products but only a few imported.  I think there were around 15 to 20 new products.

**Comment by willatkova** [comment]
@Debs123V have you got the spreadsheet they tried to import?
