### ISSUE TITLE
Mobile App - Settings Menu

### ISSUE THREAD

**Issue by Debs123V** [willatkova/makerpos-usergroup#30]
![image](https://github.com/user-attachments/assets/815b36d6-3934-4586-9955-843e7344b12f)

There is no Settings tab on the mobile app.  A Maker is having an issue with their prefix but cannot locate the settings tab on the app.

Not sure how she managed to sign up without adding a prefix.  This is for Za Zi Designs

**Comment by willatkova** [comment]
Have added settings to the app
