### ISSUE TITLE
Easier switch between users

### ISSUE THREAD

**Issue by willatkova** [willatkova/makerpos-usergroup#5]
Easier switch between users on one till.  I have 2 cashiers at a time using one login.  I’d like to have a quick switch with password for each cashier to see who did which transaction during a shift - but not a log out/log in thing, it takes too long.

**Comment by willatkova** [comment]
Click on the User Avatar, will bring up modal of other users:
![Screenshot 2024-03-12 at 14 03 33](https://github.com/willatkova/kovapos-usergroup/assets/54409295/622900b3-c394-4d6d-a159-43a090a2e7c8)

**Comment by willatkova** [comment]
![Screenshot 2024-03-12 at 14 03 38](https://github.com/willatkova/kovapos-usergroup/assets/54409295/0a98a974-a7ea-4057-b51c-3b2612d6586f)

**Comment by willatkova** [comment]
Selecting a user will prompt for password, if correct, user is changed

![Screenshot 2024-03-12 at 14 03 43](https://github.com/willatkova/kovapos-usergroup/assets/54409295/9bbfacaa-8506-460d-b8ca-308ae29a9be6)

**Comment by Debs123V** [comment]
Yes!  Seems quick and easy enough!
